apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: dependent-resources
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-rule.0: upsert after upserting pkgi
spec:
  serviceAccountName: sync-sa
  fetch:
  - git:
      ref: origin/main
      url: https://github.com/tfynes-pivotal/tap-gitops-a4dec1
      subPath: clusters/taplab/cluster-config/dependent-resources
      secretRef:
        name: sync-git
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: sync-age-identity
  - ytt: {}
  deploy:
  - kapp:
      rawOptions:
      - --dangerous-allow-empty-list-of-resources=true
